#!/bin/bash
for i in 1 2 3 4; do
  echo "Building database for shard $i..."
  mmseqs createdb data/shard_${i}.fasta data/mmseqs_db_${i}
  mmseqs createindex data/mmseqs_db_${i} /tmp --search-type 3 --spaced-kmer-mode 0
  echo "Shard $i done."
done
echo "All databases built."
